version: '3.2'

services:
  php:
    container_name: docker-php
    build: ./.docker/php/
    ports:
      - "80:80"
      - "443:443" 
    restart: always
    volumes:
      - .:/app
    links:
      - mysql

  mysql:
    container_name: docker-db
    build: ./.docker/db
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password      
    environment:       
      - MYSQL_USER = dbuser
      - MYSQL_PASSWORD = dbpass
      - MYSQL_ROOT_PASSWORD = root
      - MYSQL_DATABASE = dockerdb
      - MYSQL_ROOT_HOST = %
      - MYSQL_HOST = %
      - MYSQL_ALLOW_EMPTY_PASSWORD = true      
